#!/bin/bash
# Shared environment for the gpt-oss-120b megakernel runs.
# Sourced by run_1gpu.sh / run_mp2.sh / run_mp2_ep.sh -- not run directly.

FLEET_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# MIRAGE_HOME decides which tree the megakernel compiles against, and
# PYTHONPATH decides which one `import mirage` resolves to. A stale editable
# install (~/.local/.../__editable__.mirage_project*.pth) points at a
# *different* checkout, so both must be pinned or the run silently exercises
# the wrong codebase.
export MIRAGE_HOME="$FLEET_HOME"
export PYTHONPATH="$FLEET_HOME/python:${PYTHONPATH:-}"

export USE_FP8_ACT=1

# Set MODEL_PATH in your shell, or point HF_HOME at a cache holding the model.
export MODEL_PATH="${MODEL_PATH:?set MODEL_PATH to the gpt-oss-120b directory}"

# rocSHMEM + the MPI it was built against. rocSHMEM's IPC backend only needs
# MPI for bootstrap (rank exchange), not for the data path. Only the
# multi-GPU scripts need these; a single-GPU run never reads them.
#
# ROCSHMEM_HOME / OMPI_HOME default to $HOME/rocshmem and $HOME/ompi, which is
# where the build instructions put them. Override either if yours live
# elsewhere; if $OMPI_HOME/lib is absent we fall back to the distro OpenMPI.
ROCSHMEM_HOME="${ROCSHMEM_HOME:-$HOME/rocshmem}"
OMPI_HOME="${OMPI_HOME:-$HOME/ompi}"
UCX_HOME="${UCX_HOME:-$HOME/ucx}"
export ROCSHMEM_INC_PATH="${ROCSHMEM_INC_PATH:-$ROCSHMEM_HOME/include}"
export ROCSHMEM_LIB_PATH="${ROCSHMEM_LIB_PATH:-$ROCSHMEM_HOME/lib}"
if [ -d "$OMPI_HOME/lib" ]; then
  export MPI_INC_PATH="${MPI_INC_PATH:-$OMPI_HOME/include}"
  export MPI_LIB_PATH="${MPI_LIB_PATH:-$OMPI_HOME/lib}"
  export PATH="$OMPI_HOME/bin:$PATH"
  export LD_LIBRARY_PATH="$OMPI_HOME/lib:$UCX_HOME/lib:/opt/rocm/lib:${LD_LIBRARY_PATH:-}"
else
  export MPI_INC_PATH="${MPI_INC_PATH:-/usr/lib/x86_64-linux-gnu/openmpi/include}"
  export MPI_LIB_PATH="${MPI_LIB_PATH:-/usr/lib/x86_64-linux-gnu/openmpi/lib}"
  export LD_LIBRARY_PATH="$MPI_LIB_PATH:/opt/rocm/lib:${LD_LIBRARY_PATH:-}"
fi

# Every knob the multi-GPU path reads, forwarded to both ranks by mpirun.
# Listing them unconditionally is deliberate: -x on an unset variable is a
# no-op, so a knob set in the caller's shell reaches rank 1 without editing
# this list.
MPK_FORWARD_VARS=(
  MIRAGE_HOME PYTHONPATH USE_FP8_ACT MODEL_PATH
  HIP_VISIBLE_DEVICES ROCR_VISIBLE_DEVICES
  ROCSHMEM_INC_PATH ROCSHMEM_LIB_PATH MPI_INC_PATH MPI_LIB_PATH
  LD_LIBRARY_PATH PATH
  ROCSHMEM_MAX_NUM_CONTEXTS
  MOE_EP EP_NOAR EP_NOSLICE EP_SLOT EP_FOLD_RANK
  W13_OPW W2_OPW
  MPK_EP_ABLATE MPK_EP_SIG_DBG MPK_WORKER_STATE MPK_HOST_WATCHDOG MPK_EP9_ONLY MPK_EP_SKEW_PROBE MPK_DEVICE_TIMING
  MPK_W2_HALFK MPK_W2_SPLITK MPK_EP_WAIT_AT_USE MPK_MOE_NOPAD
  MPK_W2_CONSUMER_GATE MPK_NO_LAYER_BARRIER MPK_WIDE_FP8_QUANT MPK_ABLATE_W13_QUANT
  MPK_DRAIN_STATS MPK_ML_TABLE_PREFETCH MPK_PHASE_SLOTS MPK_PHASE_START_ITER
  MPK_INTERLAYER_SPLIT
  MPK_PREFETCH_NEXT_QKV MPK_ABLATE_QKV_DMA MPK_ABLATE_WS_FOLD
  MPK_OPROJ_NO_WB MPK_OPROJ_INNER_TIMING MPK_MOE_INNER_TIMING MPK_ATTN_NO_WAVE_LOCAL MPK_ATTN_WL_PAIR MPK_ATTN_KV_PREFETCH MPK_ATTN_SPLIT_CHUNK
  MPK_NO_FAIR_PREFILL
  MPK_XCD_LOCAL_BARRIER MPK_MFMA_PINGPONG_SCHED MPK_OPROJ_TREE_BARRIER MPK_GATE_PREV_LDS
  MPK_MOE_DUAL_ACCUMULATOR MPK_MOE_QUAD_ACCUMULATOR MPK_MOE_W2_EPILOGUE_OVERLAP
  MPK_OPROJ_KMAJOR MPK_OPROJ_PTR_WALK MPK_LM_HEAD_KMAJOR MPK_LM_HEAD_WAVE_TILE_DMA MPK_LM_HEAD_GROUP_PIPELINE MPK_QKV_LDS_NORM MPK_TOPK_LOCAL_MAX3
  MPK_EMBED_WIDE MPK_EMBED_PRODUCERS
  MPK_QKV_MFMA_UNROLLED MPK_QKV_PF_BEFORE_WAIT MPK_QKV_KSPLIT MPK_QKV_KSPLIT_SHARED_NORM MPK_QKV_SKIP_B1_WAIT MPK_QKV_ROPE_NO_BAR MPK_QKV_TSC_PTR_INCREMENT MPK_QKV_DS_BEFORE_ADDR MPK_QKV_ACC_UNDER_LDS MPK_QKV_GLOBAL_PAGE MPK_W13_T0_MFMA_UNROLLED MPK_W2_T0_MFMA_UNROLLED MPK_W2_PF_BEFORE_WAIT
  MPK_ROTATE_QKV_ATTN_RANKS MPK_QKV_ROT_OVERRIDE MPK_OPROJ_SWAP_ATTN MPK_OPROJ_PIPE_SLICE_MFMA MPK_ATTN_SLICE_RELEASE
  MPK_ATTN_SCALAR_PAGE MPK_ATTN_LDS_PINGPONG MPK_ATTN_SKIP_LAST_WAR_BAR MPK_ATTN_PF_BEFORE_PV MPK_ATTN_V_PAD8 MPK_ATTN_O_VEC_STORE MPK_ATTN_LSE_DPP MPK_ATTN_KV_NT_GL MPK_ATTN_K_VEC_LOAD MPK_ATTN_PF2 MPK_ATTN_V_AFTER_QK MPK_ATTN_PF_DURING_QK MPK_ATTN_PF_DURING_SOFTMAX MPK_ATTN_PF_AT_BAR MPK_ATTN_PV_BEFORE_LHEAD MPK_ATTN_V_COMMIT_AFTER_PV MPK_ATTN_COMMIT_BEFORE_PV MPK_ATTN_COMMIT_DURING_SOFTMAX MPK_ATTN_COMMIT_DURING_QK MPK_ATTN_QK_PIPE_K MPK_ATTN_QK_BEFORE_WAR MPK_ATTN_PERM_NO_NOP MPK_ATTN_SCORE_MAX3 MPK_ATTN_EXP2_BEFORE_OACC MPK_ATTN_LHEAD_FMA MPK_ATTN_PROLOGUE_PF_OVERLAP MPK_ATTN_UNROLL_TILES MPK_ATTN_WAVE_LOCAL_MIN_TILES
  MPK_NUM_XCDS MPK_OUTPUT_DIR MPK_WORKERS_PER_XCD MPK_DRAIN_OVERLAP MPK_W13_LINEAR_LOAD MPK_W2_LINEAR_LOAD
  MPK_W13_T1_LINEAR_LOAD MPK_W2_T1_LINEAR_LOAD MPK_W2_T1_DURING_EPI MPK_W2_SCALE_OVERLAP MPK_MOE_INNER_WIDE MPK_NDEBUG MPK_NO_SW_MASK MPK_LSE_LOG_BUG MPK_INTERLAYER_FENCE MPK_ONE_NORM_WRITER
  MPK_NO_OPROJ_SKIP_GATE MPK_MOE_ENTRY_DELAY
  MPK_W13_T1_EARLY_SCALE_LOAD MPK_QKV_PREFETCH_SCALES MPK_W13_T1_SPLIT_LDS_STAGE MPK_W13_KMAJOR_RECYCLE MPK_W13_RECYCLE_EAGER_DRAIN MPK_W13_BIAS_COUNTED_WAIT
  MPK_W13_RECYCLE_PAIR_WAIT MPK_W13_RECYCLE_EARLY_ISSUE MPK_W13_REC_NO_INNER_NOP MPK_W13_T1_NO_INNER_NOP MPK_W13_T1_ZERO_IN_T0 MPK_W13_T1_HEAD_VMCNT0 MPK_W13_T1_ACC_PAD16 MPK_W13_T1_MFMA_BEFORE_F1 MPK_W13_T0_ACC_UNDER_LDS MPK_W13_T0_LAST_REC_EARLY MPK_W13_T0_HEAD_PF_B1 MPK_W13_T0_DS_AFTER_MFMA MPK_W13_T0_B0_WAIT_SHIFT MPK_W13_T1_HEAD_PF_B1 MPK_W13_T1_B0_WAIT_SHIFT MPK_W13_SKIP_B1_WAIT MPK_W13_TSC_DS_OFFSET MPK_W13_DS_BEFORE_ADDR MPK_W13_B0_ADDR_AFTER_DS MPK_W13_REC_DOUBLE_ISSUE MPK_W13_REC_LOOP_VMCNT21 MPK_W13_REC_HEAD_VMCNT21 MPK_W13_REC_NO_NT MPK_W13_REC_DRAIN_T0 MPK_W13_REC_NO_LOOP_WAIT MPK_W13_REC_POST_WAIT MPK_W13_REC_FIFO MPK_W13_T1_HEAD_VMCNT21 MPK_W13_T1_DS_UNDER_SWIGLU MPK_W13_T1_WAIT_BEFORE_ACC MPK_W13_T1_WAIT_UNDER_STORE
  MPK_SYS_POLL_LOAD MPK_QKV_GATE_NO_AGENT_FENCE MPK_QKV_EPOCH_PRODUCER_DRAIN MPK_NARROW_GATE_POLL MPK_LAYER_GATE_BUSY_POLL MPK_SLICE_BUSY_POLL MPK_OPROJ_POLL_BEFORE_DRAIN MPK_SLICE_DUAL_POLL MPK_OPROJ_SPLIT_SLICE_WAIT MPK_OPROJ_BIAS_NO_WAIT MPK_OPROJ_RED_VEC MPK_OPROJ_NEXT_WT MPK_OPROJ_A_PAD_HOIST MPK_OPROJ_AMAX_DPP MPK_NARROW_OPROJ_HIER MPK_W13_BIAS_PREFETCH MPK_W13_T0_COUNTED_HANDOFF
  MPK_W13_BIAS_PF_T0_ONLY MPK_W13_T1_BIAS_EARLY MPK_LEAN_ARRIVE MPK_W2_ONLY_ARRIVE MPK_ROUTER_FUSED_DP MPK_ROUTER_DUAL_REDUCE MPK_ROUTER_XCD_FOLD MPK_EARLY_ROUTING MPK_MOE_XCD_PAIR MPK_ARGMAX_DUAL_REDUCE MPK_RMSNORM_DPP_REDUCE MPK_QKV_PF_WAVE_SPLIT MPK_ROPE_VEC_STORE MPK_OPROJ_LEAN_ACQUIRE MPK_MOE_PAD_ROUND MPK_MOE_XCD_STRIPE_ROT MPK_MOE_XCD_STRIPE_LAYER MPK_MOE_XCD_STRIPE_TILE MPK_MOE_BAR_BUSY_POLL MPK_W13_SCALE_GLOBAL MPK_W13_SETPRIO MPK_ATTN_SETPRIO MPK_W13_ACC_PAD16 MPK_W13_ACC_READ_OVERLAP MPK_OPROJ_SKIP_GATE_BUSY_POLL MPK_W13_PREQUANT MPK_OPROJ_ARRIVE_ONLY MPK_ROUTING_LANE_RELEASE MPK_ROUTING_DERIVED_EPOCH MPK_MERGE_KV_OUTER MPK_MERGE_TWO_PASS MPK_MERGE_WIDE_DIM MPK_MERGE_O_PRELOAD
  MPK_W13_T1_SPLIT_NOSUFFIX MPK_W13_T1_SPLIT_STAGE_PROBE MPK_W13_T1_SPLIT_PROBE_DRAIN MPK_W13_T1_SPLIT_READ_PROBE MPK_W13_T1_SPLIT_CMP MPK_W13_T1_STAGED_ROWS_OVERRIDE MPK_W13_T1_STAGE_CHUNKS_OVERRIDE
  ATTN_DP MPK_INLINE_AR2 INLINE_AR2 FUSED_MGPU_NOAR
  AR1_ELEMS_PER_BLOCK AR1_TARGET_GRID
  AR2_ELEMS_PER_BLOCK AR2_TARGET_GRID AR2_PREFETCH AR2_PREFETCH_BLOCKS
  MPK_SPAN_TIMING MPK_SUBPHASE_TIMING MPK_MOE_SUBPHASE MPK_ATT_LINEINFO
  MPK_OVERLAP_XGPU MPK_DEVICE_ACCUM
  FUSE_FULL_LAYER FUSE_FULL_LAYER_MGPU FUSE_QKV_ATTN FUSE_OPROJ_MOE
  FUSE_OPROJ_TOPK FUSE_TAIL
  PRECOMPUTED_DISPATCH USE_GANG PPL_MODE PPL_MXFP4_MATCH
  MLP_DBG MLP_FINAL_IDX
  MAX_SAVE_TOKENS
)

mpk_x_args() {
  local v
  for v in "${MPK_FORWARD_VARS[@]}"; do printf -- '-x %s ' "$v"; done
}
